#!/bin/zsh
# Make the caps lock key a control key
xmodmap -e 'keycode 66 = Control_L'
xmodmap -e 'clear Lock'
xmodmap -e 'add Control = Control_L'

if [[ "$(hostname)" =~ "xi" ]]
then
  # For the computers in the 213 lab, set the correct monitor positions
  xrandr --output DVI-I-1 --left-of HDMI-1
fi

# Handle 256 colors for vim when under tmux
alias tmux='tmux -2'

export EDITOR="vim"
