#!/usr/bin/env zsh

fpath=(/usr/local/share/zsh/site-functions $fpath)

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Local theme.
ZSH_CUSTOM="$HOME/.zsh_custom"
ZSH_THEME="rogue"

# Will be overwritten in .zshrc.local if necessary.
export EDITOR="vim"

# dircycle: use ctrl-shift-[left/right] to switch between past directories
# gnu-utils: prefer gnu-utils over builtins
# gitfast: define aliases and __git_ps1 that rogue uses
# tmuxinator: autocompletion for tmuxinator
# jump: bookmarks for the shell, use jump/mark/unmark/marks
# colored-man-pages: man pages with colors
plugins=(dircycle gnu-utils gitfast tmuxinator jump colored-man-pages)

source $ZSH/oh-my-zsh.sh

# Support the git functionality of my Rogue theme.
export GIT_PS1_SHOWDIRTYSTATE=0
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=0

alias cp='cp -Rv'
alias erc='$EDITOR ~/.zshrc'
alias rrc='source ~/.zshrc'
alias edit='$EDITOR'

alias tl='tmux list-sessions'
alias ta='tmux attach'

alias cdgr='cd $(git rev-parse --show-toplevel)'

# Don't autoset terminal title
DISABLE_AUTO_TITLE="true"

unset GREP_OPTIONS
alias grep="grep --color=always"

# Update per machine.
if [[ -e "$HOME/.zshrc.local" ]]; then
  source "$HOME/.zshrc.local"
fi

if [[ -e "$HOME/.zshrc.secret" ]]; then
  source "$HOME/.zshrc.secret"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

disable -r time
alias time='time -p'
