# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Local theme.
ZSH_CUSTOM="$HOME/.zsh_custom"
ZSH_THEME="rogue"

# Will be overwritten in .zshrc.local if necessary.
export EDITOR="vim"

plugins=(dircycle git git-extras colored-man gnu-utils autojump gitfast
         zsh-syntax-highlighting)

# Update per machine.
if [[ -e "$HOME/.zshrc.local" ]]; then
  source "$HOME/.zshrc.local"
fi

source $ZSH/oh-my-zsh.sh

# Make sure running inside of tmux.
if [[ ! $TERM =~ "screen-256color" ]]; then
  tmux -2
fi

export PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:~/bin

# Support the git functionality of my Rogue theme.
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1

alias cp='cp -Rv'
alias erc='$EDITOR ~/.zshrc'
alias sudo='sudo env PATH=$PATH'
alias rrc='source ~/.zshrc'
alias edit='$EDITOR'

# Enable 256 Colors
DISABLE_AUTO_TITLE="true"

unset GREP_OPTIONS
alias grep="grep --color=always"

eval "$(hub alias -s)"

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

alias t='todo.sh -d ~/.todo.cfg'
