#!/bin/zsh

# Download current version of oh-my-zsh and make sure it's up to date.
OMZ_DIR="$HOME/.oh-my-zsh"

if [[ -d "$OMZ_DIR" ]]; then
  echo "Oh-my-zsh found. Updating..."
  cd "$OMZ_DIR" && git pull
else
  echo "Installing oh-my-zsh..."
  git clone https://github.com/robbyrussell/oh-my-zsh.git "$OMZ_DIR"
fi

# Install neobundle

echo "Installing neobundle."

BUNDLE_DIR=~/.vim/bundle
INSTALL_DIR="$BUNDLE_DIR"/neobundle.vim
BUNDLE_GIT="https://github.com/Shougo/neobundle.vim"

if [[ -e "$INSTALL_DIR" ]]; then
  echo "Neobundle is already installed."
  exit 0
fi

mkdir -p "$BUDNLE_DIR"
git clone "$BUNDLE_GIT" "$BUNDLE_DIR/neobundle.vim"

if [[ $? -eq 0 ]]; then
  echo "Neobundle installed."
else
  echo "git clone failed with error code."
fi
