#!/bin/zsh

# Download current version of oh-my-zsh and make sure it's up to date.
OMZ_DIR="$HOME/.oh-my-zsh"

if [ -d "$OMZ_DIR" ]; then
  echo "Oh-my-zsh found. Updating..."
  cd "$OMZ_DIR" && git pull
else
  echo "Installing oh-my-zsh..."
  git clone https://github.com/robbyrussell/oh-my-zsh.git "$OMZ_DIR"
fi

# Create a sym link to the appropriate config folder
SUBL_LINK="$HOME/.sublime_config"

# Default to using default linux directory for sublime text config location
SUBL_CONF="$HOME/.config/sublime-text-3"

# OS X
if [ "$(uname)" = "Darwin" ]; then
  SUBL_CONF="$HOME/Library/Application Support/Sublime Text 3"
fi

if [ ! -e "$SUBL_LINK" ]; then
  echo "Creating sublime config link..."
  ln -s "$SUBL_CONF/Packages/User/" "$SUBL_LINK" 
fi

